# Generated by Django 4.2 on 2023-05-25 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video_and_tag', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='cover',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
